version: '3.8'

services:
  user-service:
    container_name: user-service
    build:
      context: ./microservices/user-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./user-service:/app
      - /app/node_modules
    networks:
      - microservices-network
    command: npm run dev

  product-service:
    container_name: product-service
    build:
      context: ./microservices/product-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    volumes:
      - ./product-service:/app
      - /app/node_modules
    networks:
      - microservices-network
    command: npm run dev

networks:
  microservices-network:
    driver: bridge