global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3000']
        labels:
          service: 'user-service'

  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:3001']
        labels:
          service: 'product-service'